{{- if not .Values.models.hostPath }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neuroswarm-arm.fullname" . }}-models
  labels:
    {{- include "neuroswarm-arm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.models.pvcSize }}
{{- end }}
